version: "3.4"

services:
  trpc-express-app:
    env_file: ./backend/.env
    build:
      context: ./backend
      target: builder
    ports:
      - 4000:4000
    volumes:
      - ./backend/:/server
      - /server/node_modules

    command: npm run dev

    networks:
      - test

  vite-app:
    env_file: ./frontend/.env
    build:
      context: ./frontend
      target: development
    volumes:
      - ./frontend/:/app
      - /app/node_modules
    ports:
      - 3000:3000
    command: npm run dev
    networks:
      - test

networks:
  test: {}
