version: "3.8"

services:
  trpc-express-app:
    env_file: ./backend/.env
    build:
      context: ./backend
    ports:
      - 4000:4000
    networks:
      - production

  vite-app:
    env_file: ./frontend/.env
    build:
      context: ./frontend
      target: production

    ports:
      - 3000:3000
    networks:
      - production
networks:
  production: {}
