FROM node:20-alpine as development

WORKDIR /app

COPY package*.json .

RUN npm install

COPY . .
CMD ["npm", "run", "dev"]


FROM node:20-alpine as production


WORKDIR /app


COPY package*.json .

RUN npm install

COPY . .

RUN npm run build

CMD ["npm", "run", "preview",  "--", "--host", "0.0.0.0"]

